import { createContext, useState } from "react";

export const MyContext = createContext({});

export default function GameContext({ children }) {
	const [darkMode, setDarkMode] = useState(true);
	const [monsters, setMonsters] = useState([]);
	const destroyMobs = [
		"Homunculus(Attack)",
		"Homunculus(Support)",
		"Angelmon",
		"Red Angelmon",
		"Red King Angelmon",
		"King Angelmon",
		"Blue Angelmon",
		"Blue King Angelmon",
		"Gold Angelmon",
		"Gold King Angelmon",
		"Dark Angelmon",
		"Dark King Angelmon",
		"White Angelmon",
		"White King Angelmon",
		"만랩튜토리얼보스(불)",
		"만랩튜토리얼_드래곤(불)",
		"만랩튜토리얼_가고일(물)",
		"만랩튜토리얼_가고일(불)",
		"만랩튜토리얼_가고일(바람)",
		"만랩튜토타워_방어 약화",
		"만랩튜토타워_공격 강화",
		"류(물)",
		"류(불)",
		"류(바람)",
		"류(빛)",
		"류(어둠)",
		"RYU",
		"켄(불)",
		"KEN",
		"바이슨(물)",
		"바이슨(불) ",
		"바이슨(바람)",
		"바이슨(빛)",
		"바이슨(어둠)",
		"M. BISON",
		"달심(물)",
		"달심(불)",
		"달심(바람)",
		"달심(빛)",
		"달심(어둠)",
		"DHALSIM",
		"춘리(물)",
		"춘리(불)",
		"춘리(바람)",
		"춘리(빛)",
		"춘리(어둠)",
		"CHUN-LI",
		"Ancient Intercessor",
		"Ancient Punisher",
		"Ancient Tormentor",
		"Ancient Lich King",
		"Fire Minion",
		"Kotos",
		"Guilles",
		"Leos",
		"Ancient Guardian",
		"Imperfect Samurai",
		"Imperfect Harp Magician",
		"Tower",
		"Small Crystal",
		"Medium Crystal",
		"족자(물)",
		"족자(불)",
		"족자(바람)",
		"족자(빛)",
		"족자(어둠)",
		"족자(무)",
		"하이엘리멘탈 2차 각성 보스(빛)",
		"하이엘리멘탈 2차 각성 보스(어둠)",
		"Imperfect Vampire",
		"Imperfect Magic Knight",
		"Imperfect Nine-tailed Fox",
		"Imperfect Undine",
		"Imperfect Sylph",
		"Imperfect Succubus",
		"Imperfect Joker",
		"Imperfect Ninja",
		"Imperfect Vampire",
		"Imperfect Kung Fu Girl",
		"Imperfect Horus",
		"Imperfect Neostone Agent",
		"Imperfect Dryad",
		"Otherworldly Dragon",
		"Keeper of Remains",
		"Contaminated Dragon",
		"Ath'taros",
		"Lyrith",
		"Ice Beast",
		"Fire Beast",
		"Wind Beast",
		"Light Beast",
		"Dark Beast",
		"Chaos Beast Khi'zar Kha'jul",
		"Keeper of Water",
		"Keeper of Fire",
		"Keeper of Wind",
		"Keeper of Light",
		"Keeper of Darkness",
		"Ancient Giant",
		"Legendary Dragon",
		"데몬(물)",
		"데몬(어둠)",
		"가고일(물)",
		"가고일(불)",
		"가고일(바람)",
		"가고일(빛)",
		"가고일(어둠)",
		"형상아이템용 더미(물)",
		"형상아이템용 더미(불)",
		"형상아이템용 더미(바람)",
		"형상아이템용 더미(빛)",
		"형상아이템용 더미(어둠)",
		"미궁 보스 머리",
		"미궁 보스 왼쪽팔",
		"미궁 보스 오른쪽팔",
		"미궁 룬문양 (물)",
		"미궁 룬문양 (불)",
		"미궁 룬문양 (바람)",
		"월드보스-고대골렘",
		"Fairy 2A",
		"Pixie 2A",
		"Warbear 2A",
		"Inugami 2A",
		"Werewolf 2A",
		"Martial Cat 2A",
		"Griffon 2A",
		"Dimension Predator",
		"Hollow",
		"Rainbowmon",
		"Devilmon",
		"Incarnation of Greed",
		"Incarnation of Vendetta",
		"Incarnation of Protection",
		"Taotie",
		"Turtle",
		"Super Angelmon",
		"Tartarus",
		"타워(물) - 전체 충격 수정",
		"타워(물) - 공속 게이지",
		"타워(불) - 전체 충격 수정",
		"타워(불) - 공속 게이지",
		"타워(바람) - 전체 충격 수정",
		"타워(바람) - 공속 게이지",
		"타워(빛) - 전체 충격 수정",
		"타워(빛) - 공속 게이지",
		"타워(어둠) - 전체 충격 수정",
		"타워(어둠) - 공속 게이지",
		"시험의탑 타워(왼쪽)",
		"시험의탑 타워(오른쪽)",
		"Void",
		"Predator's Wreckage",
		"2차각성 방랑 기사 수정_왼쪽(물)",
		"2차각성 방랑 기사 수정_왼쪽(불)",
		"2차각성 방랑 기사 수정_왼쪽(바람)",
		"2차각성 방랑 기사 수정_왼쪽(빛)",
		"2차각성 방랑 기사 수정_왼쪽(어둠)",
		"하이엘리멘탈 2차 각성 보스(물)",
		"하이엘리멘탈 2차 각성 보스(불)",
		"2차각성 방랑 기사 수정_오른쪽(물)",
		"2차각성 방랑 기사 수정_오른쪽(불)",
		"2차각성 방랑 기사 수정_오른쪽(바람)",
		"2차각성 방랑 기사 수정_오른쪽(빛)",
		"2차각성 방랑 기사 수정_오른쪽(어둠)",
		"2차각성 미스틱 위치 수정_왼쪽(물)",
		"2차각성 미스틱 위치 수정_왼쪽(불)",
		"2차각성 미스틱 위치 수정_왼쪽(바람)",
		"하이엘리멘탈 2차 각성 보스(바람)",
		"2차각성 하이엘리멘탈 수정_왼쪽(물)",
		"2차각성 하이엘리멘탈 수정_왼쪽(불)",
		"2차각성 하이엘리멘탈 수정_왼쪽(바람)",
		"2차각성 미스틱 위치 수정_왼쪽(빛)",
		"2차각성 미스틱 위치 수정_왼쪽(어둠)",
		"2차각성 미스틱 위치 수정_오른쪽(바람)",
		"2차각성 미스틱 위치 수정_오른쪽(빛)",
		"2차각성 미스틱 위치 수정_오른쪽(어둠)",
		"2차각성 하이엘리멘탈 수정_오른쪽(물)",
		"2차각성 하이엘리멘탈 수정_오른쪽(불)",
		"2차각성 하이엘리멘탈 수정_오른쪽(바람)",
		"2차각성 하이엘리멘탈 수정_오른쪽(빛)",
		"2차각성 하이엘리멘탈 수정_오른쪽(어둠)",
		"ROBO(물)_잔해",
		"ROBO(물)_잔해",
	];
	return (
		<>
			<MyContext.Provider
				value={{
					darkMode,
					setDarkMode,
					monsters,
					setMonsters,
					destroyMobs,
				}}
			>
				{children}
			</MyContext.Provider>
		</>
	);
}
